### ISSUE TITLE
Application android down ?

### ISSUE THREAD

**Issue by lyrixx** [2ec0b4/kaamelott-soundboard#102]
Tout d'abord **merci** pour ce site !

Sinon j'ai vu qu'il y avait une app android via le README mais le lien pointe sur une 404 :/

**Comment by 2ec0b4** [comment]
Salut,

En effet, je mettrai à jour le fichier README.md, merci pour ce retour. Et pour information, ce n'est pas moi qui ait créé cette application.

**Comment by 2ec0b4** [comment]
C'est mis à jour 😉
