### ISSUE TITLE
Comment faire un lien autoplay ?

### ISSUE THREAD

**Issue by lud** [2ec0b4/kaamelott-soundboard#125]
Le lien de partage ne joue pas automatiquement le son, il fait juste clignoter le bloc.

Le readme ne donne pas d'indications.

Merci

**Comment by 2ec0b4** [comment]
C'est une restriction de la part des navigateurs : le son n'est pas joué tant qu'il n'y a pas eu une action de la part de l'utilisateur. Le faire "clignoter" est un moyen de mettre en avant le son partagé.

Voir https://github.com/2ec0b4/kaamelott-soundboard/issues/91

**Comment by lud** [comment]
Merci. J'avais vu cette issue mais je n'avais pas l'erreur mentionnée dans la console, je me disais donc qu'il me manquait une option. Dommage pour l'autoplay.
