### ISSUE TITLE
Ajout d'une fonction aléatoire

### ISSUE THREAD

**Issue by RoyDePoy** [2ec0b4/kaamelott-soundboard#126]
Bonjour,

Un collègue aimerait avoir un bouton aléatoire, qui agirait comme lorsque l'on partage un lien.
Navigation vers l'ancre sélectionnée, et on joue le son automatiquement.

Si ça te dit, je peux faire le travail qui va avec.

**Comment by 2ec0b4** [comment]
Salut !

Ah, pourquoi pas ! Et si tu es chaud, vas-y, les _fusiodemandes_ sont ouvertes 😊

**Comment by RoyDePoy** [comment]
Salut !

J'ai fait un premier jet, que tu peux voir ici https://github.com/petosorus/kaamelott-soundboard/tree/random_button

Je me pose quelques questions.  Pour le navigate, j'ai ajouté `trigger: true` parce que sans ça, l'url changeait, mais la page ne bougeait pas.
Pour ça j'ai deux pistes :
1. Soit on laisse comme ça, la page navigue jusqu'au bon son, ça joue le automatiquement. Par contre, ça recharge tous les sons, ce qui est dommage.
1. Soit on ne navigue pas jusqu'au son, à ce moment là, je retire `trigger: true` dans le `navigate` le `trigger(sound:play)` fera le changement d'url, et je fais un `sound.play()` à la main. Ca a l'avantage de pouvoir faire plusieurs aléatoires d'affilée sans avoir à remonter en haut de page.

Je connaissais pas Backbone, et j'ai commencé à tester des choses sans trop m'occuper de nommages ou de conventions. Si tu as des points à me remonter, je te propose qu'on fasse ça sur la fusiodemande quand je l'ouvrirai.

**Comment by 2ec0b4** [comment]
Salut !

J'ai (enfin) pu tester et c'est un bon début :)

Je ne sais pas pour toi mais, dans ce contexte, je n'aime pas que l'on navigue vers le son au clic sur le bouton. Cette fonctionnalité était utile pour le partage d'une URL. Je pense qu'il faut trouver autre chose. Peut-être filtrer la liste des sons pour n'afficher que celui choisi au hasard et le jouer ? 🤔

Pour Backbone, je t'avoue que je n'en fais plus, je fais plus du Angular maintenant 😜

**Comment by RoyDePoy** [comment]
Salut !
Je suis d'accord avec toi, j'étais pas fan de cette solution mais je voulais un deuxième avis.
Celle que tu me proposes me plaît bien, je vais essayer ça :)

**Comment by RoyDePoy** [comment]
J'ai fait une nouvelle version. Tu me dis ce que tu penses du fonctionnement.

J'ai pas encore mis de style, mais je pensais ne faire apparaître le bouton reset qu'après une recherche aléatoire.

**Comment by 2ec0b4** [comment]
👋

C'est mieux je trouve 👍Effectivement, il reste un peu de style à faire. Et pense à stopper la lecture si un son est déjà en train de se jouer 😉

**Comment by 2ec0b4** [comment]
C'est fusionné : https://github.com/2ec0b4/kaamelott-soundboard/pull/127

**Comment by 2ec0b4** [comment]
Maintenant, il faut l'améliorer : https://github.com/2ec0b4/kaamelott-soundboard/issues/137 lol

**Comment by RoyDePoy** [comment]
haha
je peux m'y mettre si tu veux

**Comment by 2ec0b4** [comment]
Non t'inquiète, c'était pour plaisanter

**Comment by RoyDePoy** [comment]
ça roule :)
