### ISSUE TITLE
COmment telecharger les son SVP

### ISSUE THREAD

**Issue by Flokx38** [2ec0b4/kaamelott-soundboard#132]
Bonjour comment je peut telecharger les son mp3 svp de kaamelott pour les utilisier avec voice meeter merci a tous ?

**Comment by 2ec0b4** [comment]
Salut !
Il y a un bouton pour télécharger les source du dépôt en haut à droite, dans l'onglet "code". Tous les sons sont dans le répertoire "sounds".
