### ISSUE TITLE
Fenêtre de partage plus alignée

### ISSUE THREAD

**Issue by lburg** [2ec0b4/kaamelott-soundboard#138]
Constaté aujourd'hui, lorsque je clique sur le bouton pour afficher la fenêtre de partage d'un son, la fenêtre apparaît en bas à gauche : 

![Screenshot_2020-02-25 Kaamelott Soundboard](https://user-images.githubusercontent.com/1469023/75260520-02d99880-57ea-11ea-8866-757eef3d3948.png)

Il me suffit de zoomer/dézoomer/redimensionmer la page pour que la popup revienne au centre. Si je ferme et rouvre la popup, elle est à nouveau en bas à gauche, il faut encore changer le niveau de zoom/redimensionner la page pour que ça se réaligne. J'ai fait une capture sur un filtre pour qu'on voit facilement, mais ça me fait pareil sur la liste complète, ça apparaît tout en base de la page, à gauche.

Testé sous Firefox et Chrome, j'ai tenté de désactiver un maximum d'add-on mais j'en ai peut-être oublié, j'espère que ce n'est pas dû à l'un d'entre eux !

**Comment by 2ec0b4** [comment]
Bonjour !
OK je vois, ça ne vient pas du navigateur mais d'un plugin pour le partage sur les réseaux sociaux, je pense. Je corrigerai ça !
Merci pour ce retour

**Comment by lburg** [comment]
Pas de soucis ! D'ailleurs je me demande si ce bouton est bien pertinent au final, il suffit de copier-coller l'URL pour partager. Peut-être qu'un bouton avec un :clipboard: qui copie directement le lien dans le presse-papier serait plus utile ?

**Comment by 2ec0b4** [comment]
Hop, pas de chichi, j'ai supprimé Likely : https://github.com/2ec0b4/kaamelott-soundboard/commit/51051704afd7f13b3bf3be3435f89e15b75833c8
