### ISSUE TITLE
Normalize all files using ffmpef-normalize (EBU R128)

### ISSUE THREAD

**Issue by HugoGresse** [2ec0b4/kaamelott-soundboard#140]
J'ai constaté des différencs de volumes perçus. 
Je vous propose d'utiliser [ffmpeg-normalize](https://github.com/slhck/ffmpeg-normalize) à la place du `NormalizeSounds` via Audacity. 

On a le choix entre EBU ou RMS, j'ai fais deux trois test préliminaire et EBU ne marche pas pour les fichier de moins de 3s à moins d'utiliser [ce hack ](https://github.com/slhck/ffmpeg-normalize/issues/87#issuecomment-488944192)

Dites mois si ça vous intéresse, je pourrais traiter tout les sons déjà réalisé et update les readmes avec la marche à suivre.

**Comment by 2ec0b4** [comment]
Bonjour Hugo,

L'histoire du `NormalizeSounds` via Audacity c'était plus pour moi, je ne suis pas sûr que tout le monde l'ait utilisé. D'ailleurs, tu as remarqué des différences de volume perçu. Donc, oui, je suis intéressé pour un retraitement des fichiers ! 😊

Pour ce qui est de la mise à jour du README, je pense simplement retirer la partie parlant d'Audacity sans forcément remplacer les explications par `ffmpeg-normalize`. En revanche, j'ai en tête des actions que l'on pourrait exécuter sur des hooks Git, via des images Docker par exemple, pour que ce soit transparent pour les contributeurs, comme le tri des répliques dans le fichier JSON, le formatage du nom du fichier son et la normalisation du son donc. Mais bon, comme tout _side project_, il faut que je m'y recolle 😇

D'avance merci pour le traitement et la marche à suivre
