### ISSUE TITLE
Alexa/Action app

### ISSUE THREAD

**Issue by scastrec** [2ec0b4/kaamelott-soundboard#157]
Bonjour, 

je souhaiterais adapter ces sons sous Alexa et Google Actions. 
Ais je le droit (j'ai déjà fait un équivalent pour South Park et je me suis fait bloquer après un certain temps par les ayants droits)

Merci,

**Comment by 2ec0b4** [comment]
Bonsoir Stéphane,

Je n'ai pas véritablement de réponse à donner à cette question. Mais pour information, nous avons déjà évoqué l'aspect de la licence à utiliser pour le dépôt ici : https://github.com/2ec0b4/kaamelott-soundboard/issues/53

Au final, "c'est vous qui voyez" comme disait un Chevalier (à moins que ce ne soit l'autre). Mais je serais curieux de voir l'implémentation !

Bon codage !

**Comment by scastrec** [comment]
Merci. 
Je partagerais les apps ;-)
