### ISSUE TITLE
L'autoplay ne marche pas

### ISSUE THREAD

**Issue by Pouf842** [2ec0b4/kaamelott-soundboard#163]
Quand je clique sur une URL directe vers un son, le site s'ouvre, scrolle jusqu'au bouton du son, celui-ci s'éclaire en jaune pâle, mais le son ne se lance pas automatiquement.

Aucune idée de si c'est lié, mais j'ai cette erreur dans la console :

Error while trying to use the following icon from the Manifest: https://kaamelott-soundboard.2ec0b4.fr/favicons/android-chrome-192x192.18bb39f4.png (Download error or resource isn't a valid image)

**Comment by 2ec0b4** [comment]
C'est une restriction de la part des navigateurs : le son n'est pas joué tant qu'il n'y a pas eu une action de la part de l'utilisateur. Le faire "clignoter" est un moyen de mettre en avant le son partagé.

Voir https://github.com/2ec0b4/kaamelott-soundboard/issues/91
