### ISSUE TITLE
Certificat TLS expiré depuis le 09/08/2021

### ISSUE THREAD

**Issue by BilliAlpha** [2ec0b4/kaamelott-soundboard#167]
Il semblerait que le certificat ai expiré

![Screenshot](https://i.imgur.com/Hjckzue.png)

**Comment by 2ec0b4** [comment]
C'est corrigé ! \o/

Du coup, je vais me reposer : https://kaamelott-soundboard.2ec0b4.fr/#son/allez_vous_reposer_vous_l_avez_bien_merite
