### ISSUE TITLE
L'appli ne marche pas après npm install

### ISSUE THREAD

**Issue by lodart** [2ec0b4/kaamelott-soundboard#24]
Salut,
Alors, ça va peut être paraitre newbie, mais je n'arrive pas à faire tourner l'appli sur un VPS. Le site est accessible sans soucis, 'npm install' ne m'affiche que quelques warnings : 

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
Quand je vais sur la page, j'ai ce cercle de chargement infini. J'ai testé sur deux install fraiches de Debian et Ubuntu sans succès :/ 
Sauriez-vous d'où ça vient ?
Merci !

**Comment by munvier** [comment]
As-tu essayé dans le package.json de spécifier les versions minimum
requises pour ta version de node ? Jai cru voir une v4 de minimatch et je
ne me souviens plus de l'autre ...

**Comment by munvier** [comment]
Minimatch 3 et graceful 4, pardon ! Le repo doit être mis a jour !

Le 19 janv. 2017 9:41 PM, "Julien Verhaeghe" <echec.will.win@gmail.com> a
écrit :

> As-tu essayé dans le package.json de spécifier les versions minimum
> requises pour ta version de node ? Jai cru voir une v4 de minimatch et je
> ne me souviens plus de l'autre ...
>

**Comment by 2ec0b4** [comment]
B'soir,
Les dépendances Web sont gérées via Bower. 
npm et le package.json sont pour le build avant la mise à jour sur le serveur (non indispensable)

**Comment by lodart** [comment]
Merci beaucoup ! Un petit `Bower install`,  et ça marche ! Désolé si la question était idiote :/
