### ISSUE TITLE
Proposer de nouvelles citations...

### ISSUE THREAD

**Issue by krostif16** [2ec0b4/kaamelott-soundboard#28]
Salut, je découvre ce projet et par la même occasion cette communauté. Le résultat est effectivement hyper classe ! Je cherchais à faire un truc du genre et c'est ce qui m'a amené là. En revanche je n'avais aucune idée de comment m'y prendre ^^ J'aimerais pouvoir apporter à ce que tu as déjà fait, une grosse quantité de répliques que j'ai déjà extraites plus d'autres que j'ai en tête. J'ai tout extrait le plus proprement possible avec audacity. Par contre je ne suis pas du tout programmeur ni a l'aise avec github (j'ai à peine compris à quoi ca servait ^^) donc j'aimerais savoir comment t'apporter mes contributions voire - si tu es d'accord sur le principe - t'apporter quelques idées d'améliorations et pourquoi pas participer activement au projet. Je suis graphiste, j'aurai plaisir à apporter une touche graphique supplémentaire si cela te dis.

**Comment by 2ec0b4** [comment]
Salut @krostif16 
J'ai vu ton message sur Twitter hier, je t'ai répondu hier soir ;)
Si tes répliques sont bien référencées (personnage, épisode), tu peux me les envoyer via une plateforme genre YouSendIt et je pourrai les intégrer. Ca sera sans doute le plus simple, parce que si tu ne sais pas ce qu'est un serveur Web ou un dépôt Git, on n'est pas sorti du sable :P 
Si tu es chaud, je veux bien voir une version du soundboard par un graphiste (ce n'est mon métier non plus :D )
A bientôt

**Comment by krostif16** [comment]
Salut,
merci pour ta réponse rapide :) Je vais te faire un pack avec les répliques que j'ai déjà extraites. Il faut que je les tries un peu car certaines sont trop longues (difficile de couper parfois !) Elles sont référencées par personnages, numéros de livre et de saison. Tu me diras si tu as besoin d'une autre façon de les nomenclaturer. Pour ce qui est de faire une version graphique du soundboard je suis carrement chaud oui ! Je vais essayer de te faire des suggestions dés que possible bien que j'ai pas mal de boulot. Mais je m'y colle dés que j'ai un peu de temps parceque oui ca me botte carrement ;) A bientôt :)

Edit : Comment se fait l'insertion de nouvelles répliques dans ta soundbox ?  Est-ce manuel ou automatique ? As-tu besoin que je renseigne des meta tags pour filtrer les répliques par auteur ou par mot clef ?

**Comment by krostif16** [comment]
Re,

Voilà un premier envoi de citations pour voir si ça te convient comme ça... j'ai tout retagué avec mp3tag : 
https://we.tl/zVkxq74fW8

Lien wetransfer valable une dizaine de jours je crois ;)

Tiens moi au courant

**Comment by 2ec0b4** [comment]
Salut,
Merci.
Je n'avais pas vu ton edit dans le commentaire précédent. Les références se font manuellement dans un fichier au format JSON : https://github.com/2ec0b4/kaamelott-soundboard/blob/master/sounds/sounds.json Les meta tags ne sont pas utilisés directement mais je pourrai les utiliser pour mettre à jour le fichier.
Bon après-midi

**Comment by krostif16** [comment]
Hello,
du coup ça serait quoi le plus pratique pour les prochains envois ? Que je te joigne un fichier txt du même type à part ?

**Comment by 2ec0b4** [comment]
Salut @krostif16 
Le mieux serait que tu renseignes le fichier au format JSON, comme si tu allais faire une pull request sur Github. J'aurais alors juste un copier-coller à faire pour les ajouter :P 
Bonne journée

**Comment by krostif16** [comment]
Ouais... C'est pas faux !

**Comment by krostif16** [comment]
Voilà ^^

https://we.tl/Z09KpqI83M

J'ai pu reconstituer ça depuis mp3tag avec les fichiers config... trop pratique ^^
Dis moi si ça te va.

A part ça j'ai pas mal de boulot en ce moment mais dès que je trouve cinq minutes je t'envoi un premier jet graphique :)

**Comment by 2ec0b4** [comment]
Ça me va.
Ça marche ;)

**Comment by 2ec0b4** [comment]
https://github.com/2ec0b4/kaamelott-soundboard/commit/ff4d655c01c7dcd4b788f362bbe1c9c15a780cc3
J'ai fait un petit tri et supprimé des doublons.
Merci 👍

**Comment by krostif16** [comment]
Je viens de voir ça ^^ nickel :) Tu as bien fait de faire le tri...

PS : j'ai vu que tu étais passé sur le site on en a gros pour faire part de
ton application... Mais tu n'as pas eu beaucoup de retour bizarrement :/

Je connais bien le site pour y avoir ete un des premiers adherents. Je n'y
vais plus depuis longtemps par manque de temps (et d'actualité kaamelott il
faut bien le dire). Mais la nouvelle génération ne me semble pas aussi
chaleureuse que celle de mon époque... Dommage... Du coup j'ai téléchargé
aussi ton appli android ! Ca marche bien c'est cool ^^

Coté graphique j'y pense mais comme je t'ai dis manque de temsp cause
boulot. Donc on verra ca plus tard ;)

Merci pour tes ajouts en tous cas :)

J'en ai d'autres mais c'est vrai que ca prend du temps a trier, à splitter
etc.

Et surtout à choisir ce qui est pertinent. Sinon on voudrait tout mettre
!!!

A bientot ;)

2017-02-21 23:15 GMT+01:00 Antoine <notifications@github.com>:

**Comment by 2ec0b4** [comment]
L'[application](https://play.google.com/store/apps/details?id=fr.androdev.kaamelottsounds) n'est pas de moi, je l'ai vu passée il y a quelques semaines.
C'est quoi le lien vers le forum ?
Bonne journée

**Comment by krostif16** [comment]
http://forum.onenagros.org/

et le lien vers le post ou il présente son application :
http://forum.onenagros.org/viewtopic.php?pid=246841#p246841

Bon on peut pas dire qu'il ait piqué tes répliques vu que ce sont celles
d'Astier mais ce sont exactement les mêmes que celles qu'il y avait sur ta
soundbox. C'est pour ça que j'ai cru que ca venait de toi. Je pense qu'il à
dû les récupérer sur ta page d'une façon ou d'une autre pour éviter d'avoir
à le faire lui même...

2017-02-22 9:03 GMT+01:00 Antoine <notifications@github.com>:

**Comment by 2ec0b4** [comment]
Il y a une page "crédit" sur son appli où il mentionne ce dépôt ;)

**Comment by krostif16** [comment]
Au temps pour moi...!

En fait ça me revient, c'est quand j'ai vu ce crédit que j'ai pensé que ça
venait de toi ^^


2017-02-22 10:13 GMT+01:00 Antoine <notifications@github.com>:

**Comment by gortogg** [comment]
Rien à voir, mais si ça te va, j'ai découpé ce petit fichier, si ça te va, insère le, sinon, laisse mourir en ligne :)

https://we.tl/B5q3HHV2xy

"Sans vouloir la ramener, la seule différence concrète avec des briques, c'est que vous appelez ça des tartes!"
Lionnel Astier, Kaamelott, Livre I, Les Tartes aux myrtilles, écrit par Alexandre Astier

**Comment by 2ec0b4** [comment]
Bonsoir @gortogg 

C'est passé en _pull request_ ici : https://github.com/2ec0b4/kaamelott-soundboard/pull/64

Et la réplique est en ligne : http://kaamelott-soundboard.2ec0b4.fr/#son/difference_concrete_avec_des_briques

Merci ;)

**Comment by gortogg** [comment]
Merci à toi, juste un plaisir de mettre une petite brique/tarte à l'édifice.
