### ISSUE TITLE
Utiliser une icone de partage plus adaptée

### ISSUE THREAD

**Issue by mypplication** [2ec0b4/kaamelott-soundboard#37]
L'icone utilisée est celle de iOS, bcp bcp bcp d'users ne la connaissent pas. (ou au moins faire la bascule si iOS est detecté)

**Comment by 2ec0b4** [comment]
Je l'ai modifié avec ce commit [ef1cb40](https://github.com/2ec0b4/kaamelott-soundboard/commit/ef1cb407ba7b95bc794692b7f026a2a415f0f60f) ;)
