### ISSUE TITLE
Application iOS / Android

### ISSUE THREAD

**Issue by tnducrocq** [2ec0b4/kaamelott-soundboard#46]
Bonjour,

J'ai découvert ton site et ton repo il y a quelques temps et je tiens à te remercier.

J'ai utilisé ton repo pour créer une application iOS.
https://github.com/tnducrocq/kaamelott-sound-board-ios

En attendant la publication, les développeurs iOS peuvent installer l'application en re-compilant le projet.

**Comment by 2ec0b4** [comment]
http://kaamelott-soundboard.2ec0b4.fr/#son/wooouuuhouhouhou_c_est_mortel

Je vais tester ça !

**Comment by 2ec0b4** [comment]
Pour info, il existe une version Android : https://play.google.com/store/apps/details?id=fr.androdev.kaamelottsounds (pas de moi)

**Comment by 2ec0b4** [comment]
Beau boulot !

Bien joué le chargement dynamique des sons depuis le dépôt 👍 J'aime bien le regroupement par personnage. Je suis un peu moins convaincu par celui par épisode... mais ça permet de voir le nombre de répliques extraites par épisode.

Je vais mettre à jour le README pour ajouter un lien vers ton dépôt ;)

**Comment by tnducrocq** [comment]
Salut,
j'avais un peu de temps, j'ai fait la même appli sur Android:
https://github.com/tnducrocq/kaamelott-sound-board-android

Le déploiement est encours sur le Play Store: fr.tnducrocq.kaamelott_soundboard

**Comment by 2ec0b4** [comment]
Bonsoir,

Tu dois être au courant, mais c'est en ligne : https://play.google.com/store/apps/details?id=fr.tnducrocq.kaamelott_soundboard Faut que je trouve un Android pour tester ça :P

http://kaamelott-soundboard.2ec0b4.fr/#son/tres_bien

**Comment by Naereen** [comment]
Ca m'a l'air bien :-)
Ca plante sur mon téléphone par contre.

**Comment by MaxenceG2M** [comment]
Oh pinaise il y a une fonction "Aléatoire"  :heart_eyes: 
Marche très bien sur un Galaxy S5 New. 
Très beau travail merci beaucoup :)
