### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Ulrar** [2ec0b4/kaamelott-soundboard#50]
Salut,

Est-ce qu'il y a une API que je loupe, ou le projet d'en faire une ?
Toujours dans l’objectif de faire augmenter la productivité au boulot (bien entendu), j'aimerais écrire un petit hook dans Rocket.Chat pour venir balancer les sons directement dans le chan avec un truc style "!kaamelott c'est pas faux" en faisant une recherche et en récupérant le lien vers le fichier audio directement.

**Comment by 2ec0b4** [comment]
B'soir,
Tu n'as rien loupé, il n'y a pas d'API et je n'en prévoyais pas... mais pourquoi pas, ça m'intéresse :) Surtout si c'est pour améliorer la productivité hein, encore plus si c'est dans une start-up, hein, voilà...

**Comment by NSeydoux** [comment]
Bonjour, 
Je suis en doctorat, et je pense que la qualité et l'efficacité de la recherche de l'intégralité de mon équipe de doctorants seraient en effet améliorées par une API, pour intégrer les sons à un chat par exemple :D

**Comment by Naereen** [comment]
Ça m'intéresse aussi !

**Comment by MaxenceG2M** [comment]
Une intégration Hipchat et Slack pour encore plus de pertinence dans nos conversations professionnelles, ça me semble indispensable.

**Comment by Naereen** [comment]
@MaxenceG2M D'accord.
J'aurai pas le temps d'essayer personnellement... ([l'appli bureau](https://github.com/Naereen/kaamelott-soundboard-desktop-app) m'a déjà pris trop de temps !)

**Comment by Naereen** [comment]
Si un API venait à être codée, je veux bien m'occuper de la doc (avec [@lord/slate](https://github.com/lord/slate), c'est magnifique).

**Comment by benjaminW78** [comment]
si jamais cela vous interresse j'ai pondu un bot sur twitter qui twitte depuis les mp3 du sound board @kaamelott_today

**Comment by NSeydoux** [comment]
Ah ben oui je suis curieux. Comment récupères-tu les fichiers ?

**Comment by benjaminW78** [comment]
je fais du crawling via un server node js =>
https://github.com/benjaminW78/kaamelott-twitt-bot

je download depuis le repo github un son au hasard.

je le merge avec le sound de l'opening de kaamelott.

je le transform en mp4 avec un fond d'ecran statique relier au personnage
qui parle dans le sample telecharger. (je sais quelle sample est dl grace
au fichier sounds/sounds.json dans ce repo qui reference les noms des perso
au samples)

je craft le text du twit basé sur le sample

je verifie que dans les anciens tweets ya pas ce text de déjà présent (pour evité un reposte)

si tout est ok et pas duplicate : 
je le poste sur twitter via l'api de dev le text associer au sample.


-- 
Cordialement,

Winckell benjamin

<http://www.linkedin.com/pub/benjamin-winckell/60/b15/b29>

2017-10-03 14:51 GMT+02:00 Zwifi <notifications@github.com>:

**Comment by Naereen** [comment]
@benjaminW78 Franchement, c'est mi-classe, mi-génial, et re-mi-classe derrière.

**Comment by Naereen** [comment]
C'est encore assez loin d'une API facilement utilisable pour écrire des bots Slack ou autre, mais il y a déjà plein de choses en commun.
(je n'aurai jamais le temps de m'occuper de l'API, je préfère prévenir...)

**Comment by benjaminW78** [comment]
la effectivement mon code c'est un bot twitter avec une seul route en get pour me permettre de generer un nouveau twitt quand je veux. 
Je Pourrais ajouter une route à mon server pour généré une resource random et l'envoyer en stream.

sur slack genre via la cmd `/kaamelott`

**Comment by Ulrar** [comment]
Idéalement prendre un paramètre, l'idée de base étant quand même de pouvoir
balancer le son voulu (façon giphy audio quoi)

Le 3 oct. 2017 17:44, "winckell benjamin" <notifications@github.com> a
écrit :

**Comment by benjaminW78** [comment]
yeap je vois bien le principe, mais pour un premier test je vais faire random.
Ensuite avec params pour random dans les choix possibles pour le perso
Et enfin si j'y arrive une liste à la giphy.

**Comment by Naereen** [comment]
Cool, dis moi si tu as besoin d'un testeur (de l'API ou du bot Slack)

**Comment by Naereen** [comment]
@benjaminW78 https://www.getpostman.com/ peut aider, si besoin.

**Comment by benjaminW78** [comment]
je connais mais moi j'utilise plutot restlet en extension chrome. tkt pendant mes pauses je taff dessus le soucis la que je rencontre c'est pas le test de la route c'est que slack ne prend pas le retour que je lui envois.
mais j'ai trouvé un bon article qui va me débloqué : https://scotch.io/tutorials/create-a-custom-slack-slash-command-with-nodejs-and-express

**Comment by benjaminW78** [comment]
Update slack ne prend pas en direct un mp4 que on lui enverrai... de plus l'integration a la imgur est  faite en partenariat entre slack imgur du coup pour reproduire ca j'avoue etre dans le flou.
Jai as trouvé d'infos sur le net sur ceci

**Comment by loicbourg** [comment]
Bonjour tout le monde, 

pour info j'ai fais une petite intégration slack qui permet de lire le mp3 du lien sans avoir à se rendre sur le site. Si ca intéresse des gens de l'utiliser ou de s'en inspirer pour l'implémentation de la commande slack hésitez pas :)

https://github.com/loicbourg/kaamelott-soundboard-slack

**Comment by merwok** [comment]
Il y a aussi l’exemple de http://ouich.es/ !

**Comment by Naereen** [comment]
@merwok Je vois pas le rapport

**Comment by merwok** [comment]
C’est pas une API mais un site assez ergonomique pour accéder aux sons.
Avec les bonnes métadonnées, ça fait aussi des previews riches dans slack ou twitter.

**Comment by 2ec0b4** [comment]
J'avoue, la preview dans Twitter est top. Je vais voir pour faire la même chose.

**Comment by 2ec0b4** [comment]
Je clos cette conversation car je ne ferai manifestement pas d'API hehe

En revanche, je vais ouvrir une autre conversation pour l'amélioration des _meta_
