### ISSUE TITLE
Quelle licence ?

### ISSUE THREAD

**Issue by Naereen** [2ec0b4/kaamelott-soundboard#53]
Bonjour !
D'abord, bravo pour le projet :clap:, c'est propre, c'est classe.
> Comme dirait Perceval, « C'est trop mortel !! Whooo ! »

Juste une question : sous quelle licence est distribué le code ? Les sons ?
(Comme il n'y aucune chance d'avoir les droits sur les dits fichiers mp3, une façon de se prémunir d'une "attaque" légale serait de séparer le code et les sons, et d'en faire par exemple deux dépôts ?)
Si besoin pour choisir une licence qui vous semble approprié : http://choosealicense.com/

**Comment by 2ec0b4** [comment]
Bonsoir,

Je suis conscient que le projet n'est pas respectueux des droits d'auteur. Cela dit, je ne tire aucun autre profit que le plaisir de savoir que des fans de la série, comme moi, utilisent le site pour se remémorer de super répliques ou s'envoyer des messages entre amis / collègues... A vrai dire, je compte sur la bienveillance des ayants droit pour que ce projet perdure aussi longtemps que possible. Je rêve même qu'Alexandre Astier lui-même propose des répliques sur ce dépôt :)

C'est la raison pour laquelle je n'ai pas ajouté de licence. Et à consulter le site https://choosealicense.com/ je ne saurais pas laquelle choisir pour refléter l'état d'esprit du projet.

Merci pour votre message ;)

http://kaamelott-soundboard.2ec0b4.fr/#son/venir_foutre_votre_merde

**Comment by Naereen** [comment]
C'est un peu ce que je me disais aussi... :smiley:

http://kaamelott-soundboard.2ec0b4.fr/#son/jvous_fait_confiance
