### ISSUE TITLE
Sons parasites

### ISSUE THREAD

**Issue by AntoineTurmel** [2ec0b4/kaamelott-soundboard#61]
Par exemple sur:
http://kaamelott-soundboard.2ec0b4.fr/#son/ah_ah_mais_vous_etes_marteau_et_regardez_ca_ca_pisse_le_sang 
Facebook !

**Comment by 2ec0b4** [comment]
Bien vu. Enfin... bien entendu... Je pensais que c'était dans la scène.

Corrigé avec : https://github.com/2ec0b4/kaamelott-soundboard/pull/62
