### ISSUE TITLE
pisse_le_sang.mp3 useless and duplicate from ah_ah_mais_vous_etes_marteau_et_regardez_ca_ca_pisse_le_sang.mp3

### ISSUE THREAD

**Issue by benjaminW78** [2ec0b4/kaamelott-soundboard#65]
pisse_le_sang.mp3 do not exist inside sounds.json.
It is a shorter sample from the same sentence used for this  sound ah_ah_mais_vous_etes_marteau_et_regardez_ca_ca_pisse_le_sang
which is included inside sounds.json

i recommande to remove this sound pisse_le_sang.mp3 from the current repository

**Comment by 2ec0b4** [comment]
https://github.com/2ec0b4/kaamelott-soundboard/pull/68 corrige ça
Merci
