### ISSUE TITLE
Changer l'url dès qu'un son est joué pour favoriser le partage

### ISSUE THREAD

**Issue by munvier** [2ec0b4/kaamelott-soundboard#7]

**Comment by 2ec0b4** [comment]
Peux-tu préciser le sens de ta pensée ?

**Comment by 2ec0b4** [comment]
http://kaamelott-soundboard.2ec0b4.fr/#son/vous_la_crachez_votre_pastille

**Comment by munvier** [comment]
Lorsque je clique sur un bouton pour lire un son, j'aimerais bieng que l'url courante de la page soit modifiée avec le bon hash du son qui est en train d'être joué

**Comment by 2ec0b4** [comment]
#11 bah voilà, il l'a fait
