### ISSUE TITLE
Télécharger les sons

### ISSUE THREAD

**Issue by Leolag** [2ec0b4/kaamelott-soundboard#72]
Salut ! 
D'abord merci pour ce boulot, wahou ! Je rêvais de ça depuis des lustres, on dirait que je l'ai trouvé ! 
Ensuite j'ai un projet de mixage pour faire des discussions entre personnages de Kaamelott (voire d'autres), à base de citations cultes uniquement. 
Est-ce que c'est possible de télécharger les fichiers sur le soundcloud pour ça ? 
Merci beaucoup et bravo ! 
Léopold

**Comment by 2ec0b4** [comment]
Bonsoir Léopold,
Si j'ai bien compris, tu veux récupérer les sons sur ce dépôt pour les mettre sur soundcloud.com, c'est bien ça ? Dans la mesure où les droits d'auteur ne nous appartiennent pas (voir [mon explication ici](https://www.reddit.com/r/france/comments/5orvyf/kaamelott_soundboard_3/dcn909x/)), tu as la possibilité de les utiliser.
Antoine

**Comment by Leolag** [comment]
Bonjour, 
Je me suis mal exprimé, j'aimerais télécharger sur mon ordinateur les sons déjà postés, pour pouvoir faire un mix personnel et privé. Est-ce que c'est possible ? 
Si après, je juge mon mix assez drôle pour être publié, c'est à voir, mais je ne suis pas sûr de rendre quelque chose d'extraordinaire ! 
Merci beaucoup, 
Léo

**Comment by 2ec0b4** [comment]
Salut,
OK, je comprends :) Tu peux télécharger tout le projet à partir de ce lien : https://github.com/2ec0b4/kaamelott-soundboard/archive/master.zip Tu trouveras les sons dans le répertoire _sounds_
Tu peux éventuellement poster le résultat de ton mix sur https://www.reddit.com/r/france/ pour obtenir (ou non) une validation ;)
Bon courage

**Comment by Leolag** [comment]
Top, merci beaucoup !
