### ISSUE TITLE
Perceval: Sur une echelle

### ISSUE THREAD

**Issue by ShuP1** [2ec0b4/kaamelott-soundboard#74]
Celle la est sympa mais j'arrive pas à la retourver
```
Sur une échelle de 2 à 76, et là je préfère prendre large, de 2 à 71 on ne nous écoute pas, de 72 à 75, on nous écoute toujours pas, et seulement à 76 on nous laisse parler sans nous engueuler.
Livre IV, L’Échelle de Perceval
```

**Comment by 2ec0b4** [comment]
Alors, d'après le message, et c'est à prendre au conditionnel, il semblerait que ce soit dans le livre IV intitulé "L’Échelle de Perceval"

https://kaamelott-soundboard.2ec0b4.fr/#son/merci_de_rien

😇
