### ISSUE TITLE
Ajouter un petit ruban de pub pour un livre sur Kaamelott

### ISSUE THREAD

**Issue by Naereen** [2ec0b4/kaamelott-soundboard#76]
Si tu es d'accord @2ec0b4, pendant quelques semaines tu pourrais ajouter un petit ruban de pub sur la soundboard, pour promouvoir ce livre (http://www.editions-vendemiaire.com/catalogue/a-paraitre/kaamelott-un-livre-d-histoire-florian-besson-et-justine-breton-dir/) sur Kaamelott, qui sort très bientôt (et qui est très bien !).

Merci d'avance :-)

**Comment by Naereen** [comment]
Un petit morceau de code, comme [ce pen](https://codepen.io/eode9/pen/twkKm) peut suffire à ajouter un ruban de pub, discret.

**Comment by Naereen** [comment]
Exemple ici : https://gist.github.com/Naereen/95a10c83f5aa5645a450d97253943cc6

**Comment by 2ec0b4** [comment]
Je suis navré, je vais devoir décliner la proposition. Il n'y a (et il n'y aura) pas de publicité sur le site, ce n'est pas l'objectif.
Cela dit, bonne vente au frérot (c'est ça ? :) )

**Comment by Naereen** [comment]
Je m'en doutais, aucun problème :-)
