### ISSUE TITLE
Barre oblique manquante dans l'adresse réticulaire de partage ?

### ISSUE THREAD

**Issue by u1735067** [2ec0b4/kaamelott-soundboard#8]
https://github.com/2ec0b4/kaamelott-soundboard/blob/master/js/app/templates/sound.hbs#L4 : si on c/c ~l'url~ l'adresse réticulaire du bouton de partage, la lecture automatique ne fonctionne pas (et cela empêche même le chargement de la page je crois).

**Comment by 2ec0b4** [comment]
Bonjour @Alex131089 
C'est corrigé, je mets ça en ligne rapidement
Merci pour ce retour 👍
