### ISSUE TITLE
HTTPS invalide depuis ce matin

### ISSUE THREAD

**Issue by Naereen** [2ec0b4/kaamelott-soundboard#89]
Bonjour @2ec0b4,
Voici ce que mon navigateur me donne depuis ce matin :
```
kaamelott-soundboard.2ec0b4.fr utilise un certificat de sécurité invalide. Le certificat a expiré le 26 septembre 2018 à 10:29:29 UTC+2. La date courante est 26 septembre 2018 à 19:59.
```
Merci d'avance :+1: !

**Comment by 2ec0b4** [comment]
Bonsoir @Naereen 
C'était encore un problème de permission lors du renouvellement du certificat SSL. A vérifier lors du prochain renouvellement hehe
Merci de votre sollicitude

**Comment by Naereen** [comment]
Chouette !

**Comment by MaxenceG2M** [comment]
Hello,
Je sais pas comment tu héberges le bouzin. 
Perso j'héberge une solution Nextcloud complètement dockerisé, et pour la gestion des certificats [docker-letsencrypt-nginx-proxy-companion](j'utilise https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion).
Il vérifie régulièrement l'état de mes certificats et les renouvelles automatiquement. J'ai pas eu de problème jusqu'à maintenant.
Quand j'ai découverts ça, j'ai eu envie de... comment dire ? https://kaamelott-soundboard.2ec0b4.fr/#son/merci_de_rien

Des fois que ça puisse te donner des pistes pour te simplifier la vie :)

**Comment by 2ec0b4** [comment]
Merci pour l'info

**Comment by Naereen** [comment]
Je vais sûrement sonner pour un vieux con, mais un certificat qui se met à jour complètement automatiquement, j'ai moins confiance perso :-(
