### ISSUE TITLE
Autoplay ne fonctionne plus avec Chrome

### ISSUE THREAD

**Issue by notFloran** [2ec0b4/kaamelott-soundboard#91]
A priori depuis les dernières versions de Chrome l'autoplay des sons lors de l'ouverture d'un lien (ex: https://kaamelott-soundboard.2ec0b4.fr/#son/humilite_infiltration) n'est plus possible : le bouton du son agit comme si le son était lu mais aucun son n'est présent.

L'erreur suivante apparait dans la console : `Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`

Plus d'infos ici : https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

D'après la page y'a pas vraiment de solution, juste d'adapter un peu le js pour éviter l'erreur JS.

**Comment by 2ec0b4** [comment]
Merci pour ce retour. J'ai corrigé avec ce commit : https://github.com/2ec0b4/kaamelott-soundboard/commit/ccbbf8743d9538d346adc216e5c3612a6233280c
