### ISSUE TITLE
erreur sur le fichier chain d'audacity

### ISSUE THREAD

**Issue by kikko-rm** [2ec0b4/kaamelott-soundboard#96]
J'ai dû modifier le fichier Audacity/Chains/NormalizeSounds.txt pour qu'il soit fonctionnel en retirant les trois petits points après TrimSilence:

TrimSilence: threshold=-48.000000 min-start-silence=0.000000 min-end-silence=0.000000
Normalize: ApplyGain=yes RemoveDcOffset=yes Level=-1.000000 StereoIndependent=no
ExportMp3:

**Comment by 2ec0b4** [comment]
Je les ai supprimé https://github.com/2ec0b4/kaamelott-soundboard/commit/7b9bedeea5a81ffe3ca297c03f282f12aaefb0a6
Merci pour ce retour
